server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${USERPROFILE}\\configrepo\{application}
          search-paths:
            - 'product-service'
            - 'order-service'
