spring:
  application:
    name: shopping-cart
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
resilience4j.circuitbreaker:
  instances:
    instanceA:
      registerHealthIndicator: true