spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
    location: http://localhost:8888/product-service

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: configprops
  endpoint:
    configprops: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

